FROM python:3.11

WORKDIR /code

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 nano cron vim -y

COPY requirements/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code/

ADD crontab /etc/cron.d/crontab

RUN chmod 0644 /etc/cron.d/crontab

RUN crontab /etc/cron.d/crontab

RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log