"""empty message

Revision ID: 407134d22586
Revises: 6829d50fa10a
Create Date: 2024-10-09 14:09:21.701509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407134d22586'
down_revision = '6829d50fa10a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
